apiVersion: apps/v1
kind: Deployment
metadata:
  name: authenticate-frontend-office
spec:
  template:
    spec:
      containers:
        - name: authenticate-frontend
          image: ghcr.io/isisbusapps/authenticate-frontend@sha256:c25a6e45f1e279cd8127fb2c3e4114bd14d0ccf8c1d1924c994c718028831b5e
          volumeMounts:
            - mountPath: /front_end/config/allowed-redirects.json
              name: allowed-redirects
              subPath: allowed-redirects.json
            - mountPath: /front_end/config/internal-redirects.json
              name: internal-redirects
              subPath: internal-redirects.json
          envFrom:
            - configMapRef:
                name: authenticate-frontend-office-config
            - secretRef:
                name: authenticate-frontend-office
      volumes:
        - name: allowed-redirects
          configMap:
            name: allowed-redirects-office
        - name: internal-redirects
          configMap:
            name: internal-redirects-office
