apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: messages-service
spec:
  parentRefs:
  - name: envoy-gateway
    kind: Gateway
    namespace: envoy-gateway-system
    sectionName: https-facilities
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /messages
    backendRefs:
    - name: messages-service
      port: 30000