apiVersion: apps/v1
kind: Deployment
metadata:
  name: messages-service
spec:
  template:
    spec:
      containers:
        - name: messages-service
          image: ghcr.io/isisbusapps/messages-service@sha256:7e36e6662678851177420b889681167d5248377be9b1548c7f5892c573d5d480
          ports:
            - containerPort: 4013
