apiVersion: apps/v1
kind: Deployment
metadata:
  name: messages-service
spec:
  template:
    spec:
      containers:
        - name: messages-service
          image: ghcr.io/isisbusapps/messages-service@sha256:5cef4c549d599a6a4ffd9f99c682d91e91332381ef78a24134479323e5ce84db
          ports:
            - containerPort: 4013
