apiVersion: apps/v1
kind: Deployment
metadata:
  name: messages-service
spec:
  template:
    spec:
      containers:
        - name: messages-service
          image: ghcr.io/isisbusapps/messages-service@sha256:093322231469724633fc49535d4357d35c114ce2af73d238b859c4c43d12eb52
          ports:
            - containerPort: 4013
