apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-check-service
spec:
  template:
    spec:
      containers:
        - name: health-check-service
          image: ghcr.io/isisbusapps/health-check-service@sha256:da351f050420224187c82fb988646aece8f6e4b5fe0386ecd06b7a57f143fac8
  selector:
    matchLabels:
      app: health-check-service
