apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-check-service
spec:
  template:
    spec:
      containers:
        - name: health-check-service
          image: ghcr.io/isisbusapps/health-check-service@sha256:b4cd15a98c0e98e3bcb4e5c6a73778079d7a8a198e150e33a6d954469dabee54
  selector:
    matchLabels:
      app: health-check-service
