apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-check-service
spec:
  template:
    spec:
      containers:
        - name: health-check-service
          image: ghcr.io/isisbusapps/health-check-service@sha256:e6ba10f5b44f0adeb2a23058a820a67fe3c82db9c035129dcdbf39aada90c966
  selector:
    matchLabels:
      app: health-check-service
