{{- range $user, $config := .Values.users }}
apiVersion: rabbitmq.com/v1beta1
kind: TopicPermission
metadata:
  name: {{ $user }}-topic-permission
  namespace: {{ $.Values.namespace | default "apps" }}
spec:
  vhost: {{ $.Values.frl_exchange_vhost }}
  user: {{ $user }}
  permissions:
    exchange: {{ $config.topicPermissions.exchange | quote }}
    write: {{ $config.topicPermissions.write | default "(?!)" }}
    read: {{ $config.topicPermissions.read | default "(?!)" }}
  rabbitmqClusterReference:
    name: {{ $.Values.rmq_cluster_name }}
---
{{- end }}