apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-claims-frontend
spec:
  template:
    spec:
      containers:
        - name: user-claims-frontend
          image: ghcr.io/isisbusapps/user-claims-frontend@sha256:9f989b728e8611515ea68731bace8a3f1daba417edcd6fd6c810989287c6426d
