apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-claims-frontend
spec:
  template:
    spec:
      containers:
        - name: user-claims-frontend
          image: ghcr.io/isisbusapps/user-claims-frontend@sha256:4adddb3a6ddf0c903f77c53ab3cee39ea04babe2ab76639962c1efa956b07efd
