apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- includeSelectors: true
  includeTemplates: true
  pairs:
    app: mailchimp-webhooks

namespace: apps

resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml
