apiVersion: apps/v1
kind: Deployment
metadata:
  name: approved-experiments
spec:
  template:
    spec:
      containers:
        - name: approved-experiments
          image: ghcr.io/isisbusapps/approved-experiments@sha256:ddfc6f4a9e2f3616a396587d7729b08e0ebe1bdba418527f81fdf55ba1c5a4c0
