apiVersion: apps/v1
kind: Deployment
metadata:
  name: approved-experiments
spec:
  template:
    spec:
      containers:
        - name: approved-experiments
          image: ghcr.io/isisbusapps/approved-experiments@sha256:0dbf40caef26a3f720cc18600cf61aac85d1c39790ea91fed240e5a38cd32807
          envFrom:
            - secretRef:
                name: approved-experiments
