apiVersion: apps/v1
kind: Deployment
metadata:
  name: approved-experiments
spec:
  template:
    spec:
      containers:
        - name: approved-experiments
          image: ghcr.io/isisbusapps/approved-experiments@sha256:dba7d6e4b23fadaa4d5b22e7ae5507785e87bdea579c1d2a936d24f2efbfc1b8
