apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- ../../base
- argocd-ingress.yaml

patches:
  - path: httproute.yaml

configMapGenerator:
  - name: argocd-cm
    behavior: merge
    literals:
      - urlTest=https://devargocd.developers.facilities.rl.ac.uk