apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: rmq-message-broker
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
        # Names of clusters to deploy the app to
        - name: dev-v3
        # Uncomment if you want to deploy to dev-microk8s-alternative
        #- name: dev-microk8s-alternative
  template:
    metadata:
      name: '{{.name}}-rmq-message-broker'
      annotations:
        argocd.argoproj.io/sync-wave: "0"
        notifications.argoproj.io/subscribe.on-sync-failed.smtp-ua: users-and-auth-team@stfc365.onmicrosoft.com
        notifications.argoproj.io/subscribe.on-health-degraded.smtp-ua: users-and-auth-team@stfc365.onmicrosoft.com
        notifications.argoproj.io/subscribe.on-sync-status-unknown.smtp-ua: users-and-auth-team@stfc365.onmicrosoft.com
    spec:
      project: u-a-project
      source:
        path: Message-Broker/rmq-message-broker-chart
        repoURL: 'https://github.com/isisbusapps/users-exchange'
        targetRevision: develop
        helm:
          valueFiles:
            - values.yaml
      destination:
        namespace: apps
        name: '{{.name}}'
      syncPolicy:
        automated: 
          selfHeal: true
          enabled: true
