apiVersion: v1
data:
  user-exchange-client-config-visits.yaml: |
    exchangeConfig:
      clientName: visits-client
      republishExchange: visits_direct
      pendingQueue: visits_pending
      holdingQueue: visits_holding
      failedQueue: visits_failed
      successQueue: visits_successful
      failReasonsHeader: fail-reasons
      retryCountHeader: retry-count
      maxRetries: 5
    databaseActions:
      merge:
      - sqlStatement: UPDATE REQ_VISIT SET REQUESTER = TO_NUMBER(:newUser) WHERE REQUESTER = TO_NUMBER(:oldUser)
      - sqlStatement: UPDATE REQ_VISITOR SET USER_NUMBER = TO_NUMBER(:newUser) WHERE USER_NUMBER = TO_NUMBER(:oldUser)
      - sqlStatement: UPDATE TAXI_ADDITIONAL_PASSENGER SET USER_NUMBER = TO_CHAR(:newUser) WHERE USER_NUMBER = TO_CHAR(:oldUser)
      - sqlStatement: UPDATE USER_OFFICE_TEAM SET USER_NUMBER = TO_CHAR(:newUser) WHERE USER_NUMBER = TO_CHAR(:oldUser)
      - sqlStatement: UPDATE VISITOR SET USER_NUMBER = TO_NUMBER(:newUser) WHERE USER_NUMBER = TO_NUMBER(:oldUser)
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: user-exchange-client-config-visits
