apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: allocations-exchange-secret
  namespace: apps
spec:
  type: kv-v2
  refreshAfter: 30s
  vaultAuthRef: static-auth
  mount: reviews_and_allocations
  path: {{ $.Values.env }}/rabbitmq/allocations
  destination:
    name: allocations-exchange-secret
    overwrite: true
    create: true
    transformation:
      templates:
        username:
          text: "{{`{{ get .Secrets \"username\" }}`}}"
        password:
          text: "{{`{{ get .Secrets \"password\" }}`}}"

