apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-claims-frontend
spec:
  template:
    spec:
      containers:
        - name: user-claims-frontend
          image: ghcr.io/isisbusapps/user-claims-frontend:2.1.0
