apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: approved-experiments
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - clusters:
      selector:
        matchLabels:
          appEnvironment: prod
  template:
    metadata:
      name: '{{.name}}-approved-experiments'
    spec:
      project: r-a-project
      source:
        path: components/ra/approved-experiments/overlays/prod
        repoURL: 'https://github.com/isisbusapps/gitops'
        targetRevision: main
      destination:
        namespace: apps
        name: '{{.name}}'
      syncPolicy:
        automated: {}