apiVersion: apps/v1
kind: Deployment
metadata:
  name: proposal-factory
  namespace: apps
spec:
  template:
    metadata:
      labels:
        app: proposal-factory
    spec:
      containers:
        - name: proposal-factory
          image: ghcr.io/userofficeproject/user-office-factory@sha256:623d2e7b3ca982fcf0706de798d1c05e1821ca480f1cf00c5d21f308d1b70b44
          env:
            - name: NODE_ENV
              value: development
            - name: LOG_LEVEL
              value: info
            - name: BROWSER_WS_ENDPOINT
              value: ws://browserless.apps.svc.cluster.local:3000
            - name: FACTORY_BASE_URL
              value: http://proposal-factory.apps.svc.cluster.local:4500
            - name: MAX_CONCURRENT_PDF_GENERATIONS
              value: "15"
