apiVersion: apps/v1
kind: Deployment
metadata:
  name: proposal-factory
  namespace: apps
spec:
  template:
    metadata:
      labels:
        app: proposal-factory
    spec:
      containers:
        - name: proposal-factory
          image: ghcr.io/userofficeproject/user-office-factory@sha256:3253c3ee44919111b5feff8ad09312fb1989f70a52a0a3ce538f1b9b84c1a89b
          env:
            - name: NODE_ENV
              value: development
            - name: LOG_LEVEL
              value: info
            - name: BROWSER_WS_ENDPOINT
              value: ws://browserless.apps.svc.cluster.local:3000
            - name: FACTORY_BASE_URL
              value: http://proposal-factory.apps.svc.cluster.local:4500
            - name: MAX_CONCURRENT_PDF_GENERATIONS
              value: "15"
