apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: proposal-allocations-v2
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - clusters:
      selector:
        matchLabels:
          appEnvironment: prod
  ignoreApplicationDifferences:
    - jsonPointers:
        - /spec/syncPolicy
  template:
    metadata:
      name: '{{.name}}-proposal-allocations-v2'
    spec:
      project: r-a-project
      source:
        path: components/ra/proposal-allocations-v2/overlays/prod
        repoURL: 'https://github.com/isisbusapps/gitops'
        targetRevision: main
      destination:
        namespace: apps
        name: '{{.name}}'
      syncPolicy:
        automated: {}
