apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-check-service
spec:
  template:
    spec:
      containers:
        - name: health-check-service
          image: ghcr.io/isisbusapps/health-check-service@sha256:7a4cb76f890961f60be95371cf63130602feaf685d029bb660e93eeaa1ed11e5
  selector:
    matchLabels:
      app: health-check-service
