apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-check-service
spec:
  template:
    spec:
      containers:
        - name: health-check-service
          image: ghcr.io/isisbusapps/health-check-service@sha256:b8a84159578212e3000ed2c66e13a74433604882f122716ad6d59e1dfb7cd619
  selector:
    matchLabels:
      app: health-check-service
