apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-check-service
spec:
  template:
    spec:
      containers:
        - name: health-check-service
          image: ghcr.io/isisbusapps/health-check-service@sha256:509b2beedd39beed23235a95937b7a618770e36e730f31f60ea52ffab2242a6e
  selector:
    matchLabels:
      app: health-check-service
