{{- range .Values.admin_users.name }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ . }}-secret
spec:
  type: kv-v2
  refreshAfter: 30s
  vaultAuthRef: static-auth
  mount: user-exchange
  path: {{ $.Values.env }}/broker/users/{{ . }}
  destination:
    name: {{ . }}-secret
    create: true
    transformation:
      excludeRaw: true
      excludes:
        - ".*"
      templates:
        username:
          text: "{{`{{ get .Secrets \"username\" }}`}}"
        password:
          text: "{{`{{ get .Secrets \"password\" }}`}}"
        default_user.conf:
          text: |
            {{`{{ $user := get .Secrets "username" }}`}}
            {{`{{ $pass := get .Secrets "password" }}`}}
            {{`{{ $isAdmin := get .Secrets "isAdmin" }}`}}
            {{`{{ if eq $isAdmin "true" }}`}}
            default_user = {{`{{ $user }}`}}
            default_pass = {{`{{ $pass }}`}}
            {{`{{ end }}`}}
---
{{- end }}

apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: uex-shovel-secret
  namespace: {{ $.Values.namespace }}  
spec:
  type: kv-v2
  refreshAfter: 30s
  vaultAuthRef: static-auth
  mount: user-exchange
  path: {{ $.Values.env }}/broker/shovels
  destination:
    name: uex-shovel-secret
    overwrite: true
    create: true
---