apiVersion: rabbitmq.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: uex-shovel-secret
  namespace: {{ $.Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  type: kv-v2
  refreshAfter: 30s
  vaultAuthRef: static-auth
  mount: user-exchange
  path: dev/broker/shovels
  destination:
    name: uex-shovel-secret
    overwrite: true
    create: true
---