{{- range .Values.binding }}
apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: {{ .name | lower | replace "_" "-" }}-binding
  namespace: {{ $.Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  vhost : {{ $.Values.user_exchange_vhost }}
  source: {{ .source }}
  destination: {{ .destination }}
  destinationType: {{ $.Values.binding_destination}}
  routingKey: {{ .routing_key }}
  rabbitmqClusterReference:
    name: {{ $.Values.rmq_cluster_name }} 
---
{{ end }}