{{- range .Values.binding }}
apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: {{ .name | lower | replace "_" "-" }}-binding
  namespace: {{ $.Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  vhost : {{ index .Values "user-exchange-vhost" }}
  routingKey: {{ index . "routing-key" }}
  source: {{ .source }}
  destination: {{ .destination }}
  destinationType: {{ index . "destination-type" | default "queue"}}
  rabbitmqClusterReference:
    name: {{ $.Values.rmq_cluster_name }}
---
{{ end }}