{{- range .Values.binding }}
apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: {{ .name | lower | replace "_" "-" }}-binding
  namespace: {{ $.Values.namespace }}
spec:
  vhost: {{ $.Values.user_exchange_vhost}}
  routingKey: {{ index . "routing_key" }}
  source: {{ .source }}
  destination: {{ .destination }}
  destinationType: {{ index . "destination_type" | default "queue"}}
  rabbitmqClusterReference:
    name: {{ $.Values.rmq_cluster_name }}
---
{{ end }}