{{- range .Values.policies }}
apiVersion: rabbitmq.com/v1beta1
kind: Policy
metadata:
  name: {{ .name | lower | replace "_" "-" }}-policy
  namespace: {{ $.Values.namespace }}
spec:
  name: {{ .name }}
  pattern: {{ .pattern }}
  applyTo: {{ $.Values.policies_apply_to}}
  definition:
    {{- if index .definition "max-length" }}
    max-length: {{ index .definition "max-length" }}
    {{- end}}
    {{- if index .definition "max-length-bytes" }}
    max-length-bytes: {{ index .definition "max-length-bytes"}}
    {{- end }}
    {{- if index .definition "overflow" }}
    overflow: {{ index .definition "overflow" }}
    {{- end }}    
    {{- if index .definition "dead-letter-routing-key" }}
    dead-letter-routing-key: {{ index .definition "dead-letter-routing-key" }}
    {{- end }}
    {{- if index .definition "queue-type" }}
    queue-type: quorum
    {{- end }}
  priority: {{ $.Values.policy_priority }}
  vhost: {{ $.Values.user_exchange_vhost}}
  rabbitmqClusterReference:
    name: {{ $.Values.rmq_cluster_name }}
---    
 {{ end }}