apiVersion: rabbitmq.com/v1beta1
kind: Secret
metadata:
  name: uex-shovel-secret
  namespace: {{ $.Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "7"
type: Opaque
stringData:
  {{- if hasKey .Values "shovel-uri" }}
  srcUri: {{ index .Values "shovel-uri" }}
  destUri: {{ index .Values "shovel-uri" }}
  {{- else }}
  srcUri: {{ printf "amqp:///%s" index .Values "user-exchange-vhost" }}
  destUri: {{ printf "amqp:///%s" index .Values "user-exchange-vhost" }}
  {{- end }}
---