{{- range $client_name, $settings := .Values.userSettings }}
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: {{ $client_name }}-permission
  namespace: {{ $.Values.namespace | default "apps" }}
spec:
  vhost: {{ $settings.vhost | default $.Values.user_exchange_vhost }}
  user: {{ $client_name }}
  permissions:
    configure: {{ $settings.permissions.configure | default "(?!)" }}
    write: {{ $settings.permissions.write | default "(?!)" }}
    read: {{ $settings.permissions.read | default "(?!)" }}
  rabbitmqClusterReference:
    name: {{ $.Values.rmq_cluster_name }}
---
{{- end }}