{{- range .Values.shovel}}
apiVersion: rabbitmq.com/v1beta1
kind: Shovel
metadata:
  name: {{ .name | lower | replace "_" "-"}}-shovel
  namespace: {{ $.Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1" 
spec:
  name: {{ .name }} 
  uriSecret:
    name: uex-shovel-secret
  srcQueue: {{ index . "source-queue" }}
  destQueue: {{ index . "destination-queue" }}
  ackMode: on-confirm
  deleteAfter: never
  addForwardHeaders: false
  vhost: {{ $.Values.user_exchange_vhost}}
  rabbitmqClusterReference:
    name: {{ $.Values.rmq_cluster_name }}
  deletionPolicy: retain
---
{{ end }}