apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: approved-experiments

namespace: apps

resources:
  - deployment.yaml
  - httproute.yaml
  - service.yaml

configMapGenerator:
  - name: approved-experiments-filters
    files:
      - filters.json
    options:
      disableNameSuffixHash: true
