apiVersion: apps/v1
kind: Deployment
metadata:
  name: request-consumables
spec:
  template:
    spec:
      containers:
        - name: request-consumables
          image: ghcr.io/isisbusapps/request-consumables@sha256:448525de50ed3bc0029fca1ce7a7f06ef29fcdf066f1b3296e59c2acf01c64bc
          env:
            - name: NODE_ENV
              value: production
