apiVersion: apps/v1
kind: Deployment
metadata:
  name: request-consumables
spec:
  template:
    spec:
      containers:
        - name: request-consumables
          image: ghcr.io/isisbusapps/request-consumables:1.2.0
          env:
            - name: NODE_ENV
              value: production
          volumeMounts:
            - name: common-js
              mountPath: "/app/build/common-public/js"
              readOnly: true
      volumes:
        - name: common-views
          configMap:
            name: common-pug-views
        - name: common-js
          configMap:
            name: common-pug-content-js