apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: alloy-secrets
  namespace: alloy
spec:
  type: kv-v2
  refreshAfter: 30s
  vaultAuthRef: static-auth

  mount: fase-clusters
  path: management-dev/observability/alloy-secrets
  destination:
    name: alloy-secrets
    overwrite: true
    create: true
