apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vault-operator
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
        # Names of clusters to deploy the app to
        - name: dev-v3
        # Uncomment if you want to deploy to dev-microk8s-alternative
        - name: dev-microk8s-alternative
  ignoreApplicationDifferences:
    - jsonPointers:
        - /spec/syncPolicy
  template:
    metadata:
      name: '{{.name}}-vault-operator'
      annotations:
        argocd.argoproj.io/sync-wave: "-10"
    spec:
      project: u-a-project
      source:
        repoURL: https://helm.releases.hashicorp.com
        targetRevision: 0.10.0
        chart: vault-secrets-operator
        helm:
          releaseName: vault-operator
      destination:
        namespace: vault-operator
        name: '{{.name}}'
      syncPolicy:
        automated: 
          selfHeal: true
