apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vault-operator
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - clusters:
      selector:
        matchLabels:
          appEnvironment: dev
  ignoreApplicationDifferences:
    - jsonPointers:
        - /spec/syncPolicy
  template:
    metadata:
      name: '{{.name}}-vault-operator'
      annotations:
        argocd.argoproj.io/sync-wave: "-10"
    spec:
      project: u-a-project
      source:
        repoURL: https://helm.releases.hashicorp.com
        targetRevision: 0.10.0
        chart: vault-secrets-operator
        helm:
          releaseName: vault-operator
      destination:
        namespace: apps
        name: '{{.name}}'
      syncPolicy:
        automated: 
          selfHeal: true
