apiVersion: apps/v1
kind: Deployment
metadata:
  name: authenticate-frontend
spec:
  template:
    spec:
      containers:
        - name: authenticate-frontend
          # version: 1.1.3
          image: ghcr.io/isisbusapps/authenticate-frontend@sha256:3f0d3090210826d23cbedfb14585e9030a83750eb8bdfeaa4394db8fff165d2a
          volumeMounts:
            - mountPath: /front_end/config/allowed-redirects.json
              name: allowed-redirects
              subPath: allowed-redirects.json
            - mountPath: /front_end/config/internal-redirects.json
              name: internal-redirects
              subPath: internal-redirects.json
          envFrom:
            - configMapRef:
                name: authenticate-frontend-config
            - secretRef:
                name: authenticate-frontend
      volumes:
        - name: allowed-redirects
          configMap:
            name: allowed-redirects
        - name: internal-redirects
          configMap:
            name: internal-redirects
