apiVersion: apps/v1
kind: Deployment
metadata:
  name: authenticate-frontend
spec:
  template:
    spec:
      containers:
        - name: authenticate-frontend
          # version 0.0.1
          image: ghcr.io/isisbusapps/authenticate-frontend@sha256:34372286ced2a578b6a37e4bfdf75e4bf6c15400fca5750c905c6b2d200acdc5
          volumeMounts:
            - mountPath: /front_end/config/allowed-redirects.json
              name: allowed-redirects
              subPath: allowed-redirects.json
            - mountPath: /front_end/config/internal-redirects.json
              name: internal-redirects
              subPath: internal-redirects.json
          envFrom:
            - configMapRef:
                name: authenticate-frontend-config
      volumes:
        - name: allowed-redirects
          configMap:
            name: allowed-redirects
        - name: internal-redirects
          configMap:
            name: internal-redirects
