apiVersion: apps/v1
kind: Deployment
metadata:
  name: fap-booklet-generator
spec:
  template:
    spec:
      containers:
        - name: fap-booklet-generator
          image: ghcr.io/isisbusapps/fap-booklet-generator@sha256:1e163962f2ff71e6c5e9282dcc245a28f1bda6b3cb040a23bc6a24f7f9f19f66
