apiVersion: apps/v1
kind: Deployment
metadata:
  name: fap-booklet-generator
spec:
  template:
    spec:
      containers:
        - name: fap-booklet-generator
          image: ghcr.io/isisbusapps/fap-booklet-generator@sha256:040c0380b3677b3b0f95467f87033dc12dfce8871736b76b54f78d349c8218dd
