apiVersion: apps/v1
kind: Deployment
metadata:
  name: fap-booklet-generator
spec:
  template:
    spec:
      containers:
        - name: fap-booklet-generator
          image: ghcr.io/isisbusapps/fap-booklet-generator@sha256:3a8d55d4d301619a85cdd6a567e3b61bab9c0d3ca18946c3fe7610d36a102991
