{{- range .Values.clients.name }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: user-exchange-client-{{ . }}
  namespace: apps
spec:
  type: kv-v2
  refreshAfter: 30s
  vaultAuthRef: static-auth
  mount: user-exchange
  path: dev/client/{{ . }}
  destination:
    name: user-exchange-client-{{ . }}
    overwrite: true
    create: true
---
{{- end }}