apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-office-web-service-v2
spec:
  template:
    spec:
      initContainers:
        - name: db-updater
          image: ghcr.io/isisbusapps/users-db-updater@sha256:86b01b2bc1d5de63b6ed9e9be41864c8d0cf4b5d3159d64e5abfa4908573200d
          args: ["update"]
          env:
            - name: LIQUIBASE_COMMAND_URL
              valueFrom:
                secretKeyRef:
                  name: user-office-web-service-v2
                  key: DB_URL
            - name: LIQUIBASE_COMMAND_USERNAME
              valueFrom:
                secretKeyRef:
                  name: user-office-web-service-v2
                  key: DB_USERNAME
            - name: LIQUIBASE_COMMAND_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-office-web-service-v2
                  key: DB_PASSWORD
            - name: DEPLOYMENT_NAME
              value: "users-v2-dev"
            - name: AUTHOR
              value: "kubernetes"
      containers:
        - name: user-office-web-service
          image: ghcr.io/isisbusapps/user-office-web-service@sha256:2e77b47ac06a6a57ae8fde1586ebe590a8f8c8d0256ad14623b46f7223a0de0a
          ports:
            - containerPort: 7005
          env:
            - name: JAVA_TOOL_OPTIONS
              value: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=7005 -Djavax.net.ssl.trustStore=/deployments/cacerts.jks
