apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-office-web-service-v2
wrong:
  template:
    spec:
      initContainers:
        - name: db-updater
          image: ghcr.io/isisbusapps/users-db-updater@sha256:42c10df40ce7d9e435be71afb08003aa4fd9c4becaec55a711ecec89b1456856
          args: ["update"]
          env:
            - name: LIQUIBASE_COMMAND_URL
              valueFrom:
                secretKeyRef:
                  name: user-office-web-service-v2
                  key: DB_URL
            - name: LIQUIBASE_COMMAND_USERNAME
              valueFrom:
                secretKeyRef:
                  name: user-office-web-service-v2
                  key: DB_USERNAME
            - name: LIQUIBASE_COMMAND_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-office-web-service-v2
                  key: DB_PASSWORD
            - name: DEPLOYMENT_NAME
              value: "users-v2-dev"
            - name: AUTHOR
              value: "kubernetes"
          volumeMounts:
            - name: liquibase-config
              mountPath: /liquibase/liquibase.docker.properties
              subPath: liquibase.docker.properties
              readOnly: true
      volumes:
        - name: liquibase-config
          configMap:
            name: users-db-updater-config
      containers:
        - name: user-office-web-service
          image: ghcr.io/isisbusapps/user-office-web-service@sha256:510a1aa0d6805da4f5bde24fd99ea41a22da78f412e285098d9b460720022592
          ports:
            - containerPort: 7005
          env:
            - name: JAVA_TOOL_OPTIONS
              value: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=7005 -Djavax.net.ssl.trustStore=/deployments/cacerts.jks
spec:
  template:
    spec:
      containers:
        - image: ghcr.io/isisbusapps/user-office-web-service@sha256:53245b3631dd634d557cace36bcff41caabcec19eaf7af2885c8d7cc93a7a936
