apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-office-web-service-v2
spec:
  template:
    spec:
      initContainers:
        - name: db-updater
          image: ghcr.io/isisbusapps/users-db-updater@sha256:00a3709d9b01cafb47fc0689c47cdce2b8c6ec49fb6e05251cc4eb8ccbbb2adb
          args: ["update"]
          env:
            - name: LIQUIBASE_COMMAND_URL
              valueFrom:
                secretKeyRef:
                  name: user-office-web-service-v2
                  key: DB_URL
            - name: LIQUIBASE_COMMAND_USERNAME
              valueFrom:
                secretKeyRef:
                  name: user-office-web-service-v2
                  key: DB_USERNAME
            - name: LIQUIBASE_COMMAND_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-office-web-service-v2
                  key: DB_PASSWORD
            - name: DEPLOYMENT_NAME
              value: "users-v2-dev"
            - name: AUTHOR
              value: "kubernetes"
          volumeMounts:
            - name: liquibase-config
              mountPath: /liquibase/liquibase.docker.properties
              subPath: liquibase.docker.properties
              readOnly: true
      volumes:
        - name: liquibase-config
          configMap:
            name: users-db-updater-config
      containers:
        - name: user-office-web-service
          image: ghcr.io/isisbusapps/user-office-web-service@sha256:33bca5cbeb375e4cc4fb0d0e61b638336b1e7ec90504acfe71385f51254e0ce7
          ports:
            - containerPort: 7005
          env:
            - name: JAVA_TOOL_OPTIONS
              value: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=7005 -Djavax.net.ssl.trustStore=/deployments/cacerts.jks
