apiVersion: apps/v1
kind: Deployment
metadata:
  name: request-consumables
spec:
  template:
    spec:
      containers:
        - name: request-consumables
          image: ghcr.io/isisbusapps/request-consumables@sha256:f5ea3ed135bf650968ef0be40ab4195420c2b5b50fbc50e534878a2d2d811932
          env:
            - name: NODE_ENV
              value: development
          envFrom:
            - secretRef:
                name: request-consumables
