apiVersion: apps/v1
kind: Deployment
metadata:
  name: request-consumables
spec:
  template:
    spec:
      containers:
        - name: request-consumables
          image: ghcr.io/isisbusapps/request-consumables@sha256:3cfbda0bc1227f2e51fcdba61fc2dc86466cdf604159d9af908e66ca85883384
          env:
            - name: NODE_ENV
              value: development
          envFrom:
            - secretRef:
                name: approved-experiments
          