image_ref: ghcr.io/isisbusapps/merge-user-tool/user-exchange-client@sha256:6595dbbf1bd50fff558c4ec046c14f0b7b0bb6a575d560201aaab39157ae3ceb
clients:
  - name: users
    cm_name: user-exchange-client-config-users
  - name: era
    cm_name: user-exchange-client-config-era
  - name: schedule
    cm_name: user-exchange-client-config-schedule
