image_ref: ghcr.io/isisbusapps/merge-user-tool/user-exchange-client@sha256:e9a056a4866722ffce1705f3d4e9bb32ce0c561e933d6b0d2f9cbee067d078f7
clients:
  - name: users
    cm_name: user-exchange-client-config-users
  - name: era
    cm_name: user-exchange-client-config-era
  - name: schedule
    cm_name: user-exchange-client-config-schedule
