image_ref: ghcr.io/isisbusapps/isisbusapps/merge-user-tool/user-exchange-client@sha256:90f8eba4e52cd795627767ed8375cef815d3570536191bb8c795660307b0a891
clients:
  - name: users
    cm_name: user-exchange-client-config-users
    #  - name: facilities-eras
    #    cm_name:    
