apiVersion: apps/v1
kind: Deployment
metadata:
  name: establishment-service
spec:
  template:
    spec:
      containers:
        - name: establishment-service
          image: ghcr.io/isisbusapps/establishment-service@sha256:5cb4ec96b47bdb201e832bccf8f10c7c46d2bf73948784d559c84f477c2c144a
          ports:
            - containerPort: 4019
