apiVersion: apps/v1
kind: Deployment
metadata:
  name: establishment-service
spec:
  template:
    spec:
      containers:
        - name: establishment-service
          image: ghcr.io/isisbusapps/establishment-service@sha256:8ea93f7084a5bb219836e7a89decf5e92a29e035d7e17f0694a3237bdc498047
          ports:
            - containerPort: 4019
          env:
            - name: JAVA_TOOL_OPTIONS
              value: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=4019 -Djavax.net.ssl.trustStore=/deployments/cacerts.jks
