apiVersion: apps/v1
kind: Deployment
metadata:
  name: establishment-service
spec:
  template:
    spec:
      containers:
        - name: establishment-service
          image: ghcr.io/isisbusapps/establishment-service@sha256:cba921d968e20ac48da1be82dca92565fb7d22b40c030cf8d7ba07fbbcd6bf2a
          ports:
            - containerPort: 4019
