apiVersion: apps/v1
kind: Deployment
metadata:
  name: establishment-service
spec:
  template:
    spec:
      containers:
        - name: establishment-service
          image: ghcr.io/isisbusapps/establishment-service@sha256:313a8265ae8fff0144f9afc8b96c3a8209fe2013ac48ba4986f462007faed03a
          ports:
            - containerPort: 4019
          env:
            - name: JAVA_TOOL_OPTIONS
              value: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=4019 -Djavax.net.ssl.trustStore=/deployments/cacerts.jks
