apiVersion: apps/v1
kind: Deployment
metadata:
  name: establishment-service
spec:
  template:
    spec:
      containers:
        - name: establishment-service
          image: ghcr.io/isisbusapps/establishment-service@sha256:6ceaf4c944e568e2c0a49475b90faa1258ddb3579503914bf8e6d6f1532c9267
          ports:
            - containerPort: 4019
          env:
            - name: JAVA_TOOL_OPTIONS
              value: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=4019 -Djavax.net.ssl.trustStore=/deployments/cacerts.jks
