apiVersion: apps/v1
kind: Deployment
metadata:
  name: establishment-service
spec:
  template:
    spec:
      containers:
        - name: establishment-service
          image: ghcr.io/isisbusapps/establishment-service@sha256:5801863ab4861c519ce0e0913a1654a672ed0e3130de97a24a04a4662892c2f1
          ports:
            - containerPort: 4019
