apiVersion: apps/v1
kind: Deployment
metadata:
  name: ua-dev-tools
spec:
  template:
    spec:
      containers:
        - name: ua-dev-tools
          # version: 2.1.0
          image: ghcr.io/isisbusapps/ua-dev-tools:2.1.0
