apiVersion: apps/v1
kind: Deployment
metadata:
  name: ua-dev-tools
spec:
  template:
    spec:
      containers:
        - name: ua-dev-tools
          # version: 2.3.0
          image: ghcr.io/isisbusapps/ua-dev-tools@sha256:aabbec158713fdff195e2aa7d063edb177c33a2580d9e697a99eee05259ca47c
          envFrom:
            - configMapRef:
                name: ua-dev-tools
