apiVersion: apps/v1
kind: Deployment
metadata:
  name: ua-dev-tools
spec:
  template:
    spec:
      containers:
        - name: ua-dev-tools
          # version: 2.4.0
          image: ghcr.io/isisbusapps/ua-dev-tools@sha256:f8e19de7d8d15cfb9df96bc10200ce8acbb54cb8c8b2e139a22028d2a073cd02
          envFrom:
            - configMapRef:
                name: ua-dev-tools
