apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: user-office-core-factory-app
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - clusters:
      selector:
        matchLabels:
          appEnvironment: dev
  ignoreApplicationDifferences:
    - jsonPointers:
        - /spec/syncPolicy
  template:
    metadata:
      name: '{{.name}}-user-office-core-factory-app'
    spec:
      project: submissions-project
      source:
        path: components/shared/user-office-core-factory/overlays/dev
        repoURL: https://github.com/isisbusapps/gitops
        targetRevision: main
      destination:
        namespace: apps
        name: '{{.name}}'
      syncPolicy:
        automated:
          selfHeal: true
