apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: user-establishment-details
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - clusters:
      selector:
        matchLabels:
          appEnvironment: prod
  template:
    metadata:
      name: '{{.name}}-user-establishment-details'
      annotations:
        argocd.argoproj.io/sync-wave: "0"
    spec:
      project: u-a-project
      source:
        path:  components/ua/user-establishment-details/overlays/prod
        repoURL: 'https://github.com/isisbusapps/gitops'
        targetRevision: main
      destination:
        namespace: apps
        name: '{{.name}}'
      syncPolicy:
        automated: 
          selfHeal: true