apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-exchange-publisher
spec:
  template:
    spec:
      containers:
        - name: user-exchange-publisher
          image: ghcr.io/isisbusapps/merge-user-tool/user-exchange-publisher@sha256:10ac8798406c5e9f8fbcee2e1cdbed94babf73b2d7247145dfbe98fbdbe82223
      initContainers:
        - name: setup-h2-permissions
          image: ghcr.io/isisbusapps/merge-user-tool/user-exchange-publisher@sha256:d22d6b341d14459be889bdb87873bd6930d7fa375b7a19409bfc3e7250e03b8d
