apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mimir
  namespace: argocd
spec:
  project: infrastructure-project
  sources:
    - repoURL: 'https://grafana.github.io/helm-charts'
      chart: mimir-distributed
      targetRevision: 6.0.* #Chart version
      helm:
        releaseName: mimir
        valueFiles:
        - $values/lgtm/mimir/helm-values/values.yaml
    - repoURL: https://github.com/isisbusapps/observability
      targetRevision: develop
      ref: values
  destination:
    namespace: lgtm
    name: infra
  syncPolicy:
    automated: 
      selfHeal: true