# metadata.name
rmq_cluster_name: "rmq-message-broker"

# namespace - needs to be same across all entities
namespace: "apps"

admin_secret: "uex-admin-secret"

# ensures cluster operator doesnt use latest images
image: "rabbitmq:4-management"