apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: rabbitmq-operator
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
        # Names of clusters to deploy the app to
        - name: dev-v3
        # Uncomment if you want to deploy to dev-microk8s-alternative
        #- name: dev-microk8s-alternative
  template:
    metadata:
      name: rabbitmq-operator      
    spec:
      project: u-a-project
      source:
        path: components/infra/rabbitmq-operators/operators/cluster-operator
        repoURL: 'https://github.com/isisbusapps/gitops'
        targetRevision: main
      destination:
        namespace: rabbitmq-operators
        name: '{{.name}}'
      syncPolicy:
        automated: 
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true  