{{- range .Values.users }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ .username }}-secret
spec:
  type: kv-v2
  refreshAfter: 30s
  vaultAuthRef: static-auth
  mount: user-exchange
  path: dev/broker/users/{{ .username }}
  destination:
    name: {{ .username }}-secret
    create: true
    transformation:
      excludeRaw: true
      excludes:
        - ".*"
      templates:
        username:
          text: "{{`{{ get .Secrets \"username\" }}`}}"
        password:
          text: "{{`{{ get .Secrets \"password\" }}`}}"
        default_user.conf:
          text: |
            {{`{{ $user := get .Secrets "username" }}`}}
            {{`{{ $pass := get .Secrets "password" }}`}}
            {{`{{ $isAdmin := get .Secrets "isAdmin" }}`}}
            {{`{{ if eq $isAdmin "true" }}`}}
            default_user = {{`{{ $user }}`}}
            default_pass = {{`{{ $pass }}`}}
            {{`{{ end }}`}}
---
{{- end }}