apiVersion: v1
kind: ConfigMap
metadata:
  name: user-office-web-service-v2-config
  namespace: apps

data:
  application.properties: |-
    UserAccountActivationURL=https://users.facilities.rl.ac.uk/auth/VerifyAccount.aspx?id=
    UserAccountPasswordResetURL=https://users.facilities.rl.ac.uk/auth/ResetPassword.aspx?id=

    quarkus.rest-client.mailchimp-api.url=https://external-api.facilities.rl.ac.uk/mailchimp
    quarkus.rest-client.merge-user-tool-api.url=https://apis.facilities.rl.ac.uk/users/merges

    DATABASE_SERVER_LATENCY_EXPIRY_MINS=60

    quarkus.otel.exporter.otlp.endpoint=http://alloy.alloy.svc.cluster.local:4317

    JWT.publicKey=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAx653Gv4kx1I5fsJju/Ame7674HJAjsheIthRuT9RS96vrvyUyc3B+FTTXAyNvtY5jsJoUY9o/4YhbB4Ep8GrL9h3rmZjxIGLv8jPfyYYqV874t5xvSf0Bcew4c+Rc41vVWaQPaEqYkyBJ9sLnI/TWatS1Zbw0lFc5S5gxzealYaDLj3xLtoAEDoYwyoDS1AMxWK1IEFOYtdAwGyPBkR51xodyY0Hi+uu9sPx++lJ/Vokw66K79puakNqOa0pCMuon4h44/8b382aLb5yNXijWjqgfJN0oEYlXRjdCOIRSXyGACwozRrD7xHyT7nFC0NEmpK8UWC9kiBLlgtJS6HElwIDAQAB
