apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-office-web-service-v2
spec:
  template:
    spec:
      initContainers:
        - name: db-updater
          image: ghcr.io/isisbusapps/users-db-updater@sha256:5f817344df876351793795ec470a2c301c37adf754c035222e4c7bae4c1207db
          args: ["update"]
          env:
            - name: LIQUIBASE_COMMAND_URL
              valueFrom:
                secretKeyRef:
                  name: user-office-web-service-v2
                  key: DB_URL
            - name: LIQUIBASE_COMMAND_USERNAME
              valueFrom:
                secretKeyRef:
                  name: user-office-web-service-v2
                  key: DB_USERNAME
            - name: LIQUIBASE_COMMAND_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-office-web-service-v2
                  key: DB_PASSWORD
            - name: DEPLOYMENT_NAME
              value: "users-v2-prod"
            - name: AUTHOR
              value: "kubernetes"
          volumeMounts:
            - name: liquibase-config
              mountPath: /liquibase/liquibase.docker.properties
              subPath: liquibase.docker.properties
              readOnly: true
      volumes:
        - name: liquibase-config
          configMap:
            name: users-db-updater-config
      containers:
        - name: user-office-web-service
          # version: 2.5.0-alpha
          image: ghcr.io/isisbusapps/user-office-web-service@sha256:8ccb4985331782bd73dfe62459376edf1bca3bd028208b8bd727496e4b38e067
          env:
            - name: JAVA_TOOL_OPTIONS
              value: -Djavax.net.ssl.trustStore=/deployments/cacerts.jks
