apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: keydb

resources:
- configmap.yaml
- deployment.yaml
- service.yaml
- replication-service.yaml

labels:
- pairs:
    app.kubernetes.io/name: keydb
    app.kubernetes.io/component: cache
    environment: prod
  includeSelectors: true
