apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  template:
    spec:
      containers:
        - name: auth-service
          # version: 1.6.0
          image: ghcr.io/isisbusapps/auth-service@sha256:29fbe1863a38dc894189411d76b7bd7992f1fadbc48e83b28bc64a0cd81d9a83
