apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  template:
    spec:
      containers:
        - name: auth-service
          image: harbor.stfc.ac.uk/isisbusapps/auth-service:1.2.0