
frl_exchange_vhost: fap-results-letters

users:
  fap-results-letters-user:
    tags:
     - management
    permissions:
      configure: .*
      write: .*
      read: .*
    topicPermissions:
      exchange:
      write: .*
      read: .*
     
exchange:
 - name: fap-results-letters.fanout
   type: fanout

queue:
 - name: fap-results-letters

binding:
- name: fap-results-letters
  source: fap-results-letters.fanout
  destination: fap-results-letters
  destination_type: queue