apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- includeSelectors: true
  includeTemplates: true
  pairs:
    app: user-establishment-details

namespace: apps

resources:
  - deployment.yml
  - ingress.yml
  - service.yml
