apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  template:
    spec:
      containers:
        - name: auth-service
          image: ghcr.io/isisbusapps/auth-service@sha256:0b23a9b981940a69e691bb528d72b66155e9ab7692039466d3c79f4fb75841ba
          ports:
            - containerPort: 5005
