apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  template:
    spec:
      containers:
        - name: auth-service
          image: ghcr.io/isisbusapps/auth-service@sha256:2d7c8d3d942293a6598d0d20c9bde7084db97c6a541ddf90e1d1ee622324331e
          ports:
            - containerPort: 5005
          envFrom:
            - secretRef:
                name: auth-service
