apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  template:
    spec:
      containers:
        - name: auth-service
          image: ghcr.io/isisbusapps/auth-service@sha256:f32881ea39082df899e17d8ddcb89f8ce0ce8d28851385442409ad3e9ba66c43
          ports:
            - containerPort: 5005
