apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  template:
    spec:
      containers:
        - name: auth-service
          image: ghcr.io/isisbusapps/auth-service@sha256:f8188c2d1423613aa383ab62c3ae6310cd3e572b7b4d46750e07ef3fe0c80042
          ports:
            - containerPort: 5005
          envFrom:
            - secretRef:
                name: auth-service
