apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  template:
    spec:
      containers:
        - name: auth-service
          image: ghcr.io/isisbusapps/auth-service@sha256:406250615af266e69730c87cfddd0006de6d7f598032317af49bb3c7ae697f63
          ports:
            - containerPort: 5005
          envFrom:
            - secretRef:
                name: auth-service
