apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-office-web-service-v1
spec:
  template:
    spec:
      containers:
        - name: user-office-web-service
          # version: 1.6.3
          image: ghcr.io/isisbusapps/user-office-web-service@sha256:e61ea9e2978dd4ba22274182cbbe420d1c727667b8afbc96f6a41eb94476900e
          env:
            - name: JAVA_TOOL_OPTIONS
              value: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=7005 -Djavax.net.ssl.trustStore=/deployments/cacerts.jks
