apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: management-dev-vault-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
    project: infrastructure-project
    source:
      repoURL: https://helm.releases.hashicorp.com
      targetRevision: 0.10.0
      chart: vault-secrets-operator
      helm:
        releaseName: vault-operator
    destination:
      namespace: vault-operator
      server: https://kubernetes.default.svc
    syncPolicy:
      automated:
        selfHeal: true
      syncOptions:
        - CreateNamespace=true