apiVersion: apps/v1
kind: Deployment
metadata:
  name: approved-experiments
spec:
  template:
    spec:
      containers:
        - name: approved-experiments
          image: ghcr.io/isisbusapps/approved-experiments@sha256:ab80b944b21d4ec0b0cdffeb7fdb7d10dff55b8e2a7862a22689560a52d4180f
