apiVersion: apps/v1
kind: Deployment
metadata:
  name: approved-experiments
spec:
  template:
    spec:
      containers:
        - name: approved-experiments
          image: ghcr.io/isisbusapps/approved-experiments:1.8.1
          volumeMounts:
            - name: common-js
              mountPath: "/app/build/common-public/js"
              readOnly: true
      volumes:
        - name: common-views
          configMap:
            name: common-pug-views
        - name: common-js
          configMap:
            name: common-pug-content-js
