apiVersion: apps/v1
kind: Deployment
metadata:
  name: approved-experiments
spec:
  template:
    spec:
      containers:
        - name: approved-experiments
          image: ghcr.io/isisbusapps/approved-experiments@sha256:70b2c8a82dd8a582d262cb4590f96e949273d7879705fab5a10ec67afdb1b6a6
          env:
            - name: CONFIG_PATH
              value: /FBS/.env
          volumeMounts:
            - name: env-config
              mountPath: "/FBS"
              readOnly: true
      volumes:
        - name: env-config
          secret:
            secretName: approved-experiments-environment
