apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: approved-experiments
  namespace: apps
spec:
  type: kv-v2
  refreshAfter: 30s
  vaultAuthRef: static-auth

  mount: reviews_and_allocations
  path: prod/approved-experiments
  destination:
    name: approved-experiments
    overwrite: true
    create: true
