{{- range .Values.queue}}
apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: {{ .name | lower }}
  namespace: {{ $.Values.namespace }}
spec:
  name: {{ .name }} 
  autoDelete: {{ index . "auto-delete" | default "false" }}
  durable: {{ .durable | default "true" }}
  type: quorum
  vhost: {{ $.Values.uop_exchange_vhost}}
  rabbitmqClusterReference:
    name: {{ $.Values.rmq_cluster_name }}
  deletionPolicy: retain
---
{{ end }}