apiVersion: rabbitmq.com/v1beta1
kind: Vhost
metadata:
  name: {{ $.Values.uop_exchange_vhost }}
  namespace: {{ $.Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  name: {{ $.Values.uop_exchange_vhost }}
  defaultQueueType: quorum   # quorum | classic | stream
  rabbitmqClusterReference:
    name: {{ $.Values.rmq_cluster_name }}
  deletionPolicy: retain   
  