apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-exchange-publisher
spec:
  revisionHistoryLimit: 3 
  selector:
    matchLabels:
      app: user-exchange-publisher      
  replicas: 1
  template:
    metadata:
      labels:
        app: user-exchange-publisher       
    spec:
      initContainers:
        - name: setup-h2-permissions
          image: ghcr.io/isisbusapps/user-exchange-publisher@sha256:2f8f729328f4eb48163fe5c69e8d94253ff45e5e318c89e17ccd85523c6551b8
          command: ["/bin/sh", "/scripts/setup_h2_permissions.sh"]
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          volumeMounts:
            - name: data
              mountPath: /data
            - name: script
              mountPath: /scripts
              readOnly: true
      containers:
        - name: user-exchange-publisher
          image: ghcr.io/isisbusapps/user-exchange-publisher@sha256:2f8f729328f4eb48163fe5c69e8d94253ff45e5e318c89e17ccd85523c6551b8
          ports:
            - containerPort: 8080            
          volumeMounts:
            - name: data
              mountPath: "/data"                       
          envFrom:
            - secretRef:
                name:  user-exchange-publisher
          securityContext:
            runAsUser: 773
            runAsGroup: 773
                      
      imagePullSecrets:
        - name: registry-creds
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: user-exchange-publisher-data-pvc
        - name: script
          configMap:
            name: setup-h2-permissions
            defaultMode: 0755    # makes script executable    
