apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: merge-user-publisher-secrets
  namespace: apps
spec:
  type: kv-v2
  refreshAfter: 30s
  vaultAuthRef: static-auth

  mount: users-and-auth
  path: dev/merge-user-publisher
  destination:
    name: merge-user-publisher
    overwrite: true
    create: true
