apiVersion: apps/v1
kind: Deployment
metadata:
  name: authenticate-frontend
spec:
  template:
    spec:
      containers:
        - name: authenticate-frontend
          image: ghcr.io/isisbusapps/authenticate-frontend@sha256:bd91700388ef6bf398a8188f66f307aa623a3d5b27c22efb03d223e3bae8e48f
          volumeMounts:
            - mountPath: /front_end/config/allowed-redirects.json
              name: allowed-redirects
              subPath: allowed-redirects.json
            - mountPath: /front_end/config/internal-redirects.json
              name: internal-redirects
              subPath: internal-redirects.json
          envFrom:
            - configMapRef:
                name: authenticate-frontend-config
            - secretRef:
                name: authenticate-frontend
      volumes:
        - name: allowed-redirects
          configMap:
            name: allowed-redirects
        - name: internal-redirects
          configMap:
            name: internal-redirects
