apiVersion: apps/v1
kind: Deployment
metadata:
  name: authenticate-frontend
spec:
  template:
    spec:
      containers:
        - name: authenticate-frontend
          image: ghcr.io/isisbusapps/authenticate-frontend@sha256:16a26effe13d0d0d95df987bbbbe835235ab3ea71ba50c00b7b238fb115fe64e
