apiVersion: apps/v1
kind: Deployment
metadata:
  name: authenticate-frontend
spec:
  template:
    spec:
      containers:
        - name: authenticate-frontend
          image: ghcr.io/isisbusapps/authenticate-frontend@sha256:717a8117691173111963fa088099fd9eb6307036b7331f3da46f0ca006dfde41
          volumeMounts:
            - mountPath: /front_end/config/allowed-redirects.json
              name: allowed-redirects
              subPath: allowed-redirects.json
      volumes:
        - name: allowed-redirects
          configMap:
            name: allowed-redirects
