apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-establishment-details
spec:
  template:
    spec:
      containers:
        - name: user-establishment-details
          image: ghcr.io/isisbusapps/user-establishment-details@sha256:104300a3259d5d8548a20eec4c7a750942cfd7f73f69ecbe60bab13a237d160c
          envFrom:
            - configMapRef:
                name: user-establishment-details
