apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-establishment-details
spec:
  template:
    spec:
      containers:
        - name: user-establishment-details
          image: ghcr.io/isisbusapps/user-establishment-details@sha256:8cfd1c20c19541288dbf6e32701810b03874aec031e72cf2efc7c5ae020de548
          envFrom:
            - configMapRef:
                name: user-establishment-details
