apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-establishment-details
spec:
  template:
    spec:
      containers:
        - name: user-establishment-details
          image: ghcr.io/isisbusapps/user-establishment-details@sha256:4c23ffe0140c3caa0e999f21b2b2d5e3fdcd4308403c0ddc556d1fd51ae63259
          envFrom:
            - configMapRef:
                name: user-establishment-details
