apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-establishment-details
spec:
  template:
    spec:
      containers:
        - name: user-establishment-details
          image: ghcr.io/isisbusapps/user-establishment-details@sha256:8427f2512dbe7945ffe2ed25127fbc782aa76fce45bc9f409e4249619027d27b
