apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-establishment-details
spec:
  template:
    spec:
      containers:
        - name: user-establishment-details
          image: ghcr.io/isisbusapps/user-establishment-details@sha256:0036110045ec50113a38c88be7ce814cfa7780166ddb9d32184324ae5b454aab
          envFrom:
            - configMapRef:
                name: user-establishment-details
