apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-establishment-details
spec:
  template:
    spec:
      containers:
        - name: user-establishment-details
          image: ghcr.io/isisbusapps/user-establishment-details@sha256:c80a9140b3f097477f32b3dc2b0ced0591efd163f9d97bf9963b5887aa14d1f6
          envFrom:
            - configMapRef:
                name: user-establishment-details
