apiVersion: apps/v1
kind: Deployment
metadata:
  name: ua-dev-tools
spec:
  template:
    spec:
      containers:
        - name: ua-dev-tools
          image: ghcr.io/isisbusapps/ua-dev-tools@sha256:a373647b3b5b54c493e129795c3100faa0606dc84991935a855f4b92f221c08f
          envFrom:
            - configMapRef:
                name: ua-dev-tools
