apiVersion: apps/v1
kind: Deployment
metadata:
  name: ua-dev-tools
spec:
  template:
    spec:
      containers:
        - name: ua-dev-tools
          image: ghcr.io/isisbusapps/ua-dev-tools@sha256:e0b338f47d80fe6fd0f4a375f653beecd44a6547de7ab9d8db5c5f57cc6810f3
          envFrom:
            - configMapRef:
                name: ua-dev-tools
