apiVersion: apps/v1
kind: Deployment
metadata:
  name: ua-dev-tools
spec:
  template:
    spec:
      containers:
        - name: ua-dev-tools
          image: ghcr.io/isisbusapps/ua-dev-tools@sha256:28a844673540b2caa4ad13f343853c50504f5b51fe4cd59504dfa144e28c2d24
          envFrom:
            - configMapRef:
                name: ua-dev-tools
