apiVersion: apps/v1
kind: Deployment
metadata:
  name: ua-dev-tools
spec:
  template:
    spec:
      containers:
        - name: ua-dev-tools
          image: ghcr.io/isisbusapps/ua-dev-tools@sha256:652fe1281fae967b83a6c9538c8a751c03a7f884b91be32bc5061aaaa2465dfc
