apiVersion: apps/v1
kind: Deployment
metadata:
  name: ua-dev-tools
spec:
  template:
    spec:
      containers:
        - name: ua-dev-tools
          image: ghcr.io/isisbusapps/ua-dev-tools@sha256:e0c461c71c23f5e13898234144b52bb9d07322de5ae33aad95ca38f8c94e7084
          envFrom:
            - configMapRef:
                name: ua-dev-tools
