apiVersion: apps/v1
kind: Deployment
metadata:
  name: ua-dev-tools
spec:
  template:
    spec:
      containers:
        - name: ua-dev-tools
          image: ghcr.io/isisbusapps/ua-dev-tools@sha256:3a8a3ebedcb8bfd829a90b1301655d9696e475a4cc92d1e3903bd2c30bc2ab42
