# For Admin user
{{- range .Values.admin_users.name }}
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: {{ . }}-user
  namespace: {{ $.Values.namespace }}
spec:  
  {{- $userSettings := index $.Values.userSettings . }} 
  {{- if $userSettings.tags}}  
  tags:
  {{- range $userSettings.tags }}
    - {{ . }}
  {{- end }}
  {{- end }}
  importCredentialsSecret:
    name: {{ . }}-secret
  rabbitmqClusterReference:
    name: {{ $.Values.rmq_cluster_name }} 
---
{{- end }}    