apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: infrastructure-project
  sources:
    - repoURL: 'https://grafana-community.github.io/helm-charts'
      chart: grafana
      targetRevision: 12.4.* #Chart version
      helm:
        releaseName: grafana
        valueFiles:
        - $values/lgtm/grafana/helm-values/values.yaml
    - repoURL: https://github.com/isisbusapps/observability
      targetRevision: develop
      ref: values
  destination:
    namespace: lgtm
    name: infra
  syncPolicy:
    automated: 
      selfHeal: true