apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps-gitops
  namespace: argocd
spec:
  project: infrastructure-project
  source:
    path: argocd/prod
    repoURL: https://github.com/isisbusapps/gitops
    targetRevision: main
    directory:
      recurse: true
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    syncPolicy:
      automated: 
        selfHeal: true