apiVersion: apps/v1
kind: Deployment
metadata:
  name: establishment-service
spec:
  template:
    spec:
      containers:
        - name: establishment-service
          # version: 0.1.0
          image: ghcr.io/isisbusapps/establishment-service@sha256:cfa230ac6292213ae0d83a68727d45723090ac48bac96d639053d61c61c5dce9
          ports:
            - containerPort: 4019
