apiVersion: v1
data:
  user-exchange-client-config-allocations.yaml: |
    exchangeConfig:
      clientName: allocations-client
      republishExchange: allocations_direct
      pendingQueue: allocations_pending
      holdingQueue: allocations_holding
      failedQueue: allocations_failed
      successQueue: allocations_successful
      failReasonsHeader: fail-reasons
      retryCountHeader: retry-count
      maxRetries: 5
    databaseActions:
      merge:
      - sqlStatement: CALL ReplaceUser(:oldUser, :newUser)
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: user-exchange-client-config-allocations
