apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-claims-backend
spec:
  template:
    spec:
      containers:
        - name: user-claims-backend
          image: ghcr.io/isisbusapps/user-claims-backend@sha256:0ddab7bb77108ec4a25e3424153ca27e2700bb1d669cdc5e91ef1ca8d403d84e
