apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-claims-backend
spec:
  template:
    spec:
      containers:
        - name: user-claims-backend
          image: ghcr.io/isisbusapps/user-claims-backend@sha256:da5171af11c642a18b250b35ce97830c7678879e08a981ef0200dcce7ba72e82
