apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: user-claims-backend
  namespace: apps
spec:
  type: kv-v2
  refreshAfter: 30s
  vaultAuthRef: static-auth

  mount: reviews-and-allocations
  path: dev/user-claims-backend
  destination:
    name: user-claims-backend
    overwrite: true
    create: true
    