apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: {{ $.Values.rmq_cluster_name }}
  namespace: {{ $.Values.namespace }}
  annotations:
    rabbitmq.com/topology-allowed-namespaces: "apps"
spec:
  replicas: 1
  override:
    service:
      spec:
        ports:
          - name: epmd # adds an additional port on the service
            protocol: TCP
            port: 4369
    statefulSet:
      spec:
        template:
          spec:           
            containers:
              - name: rabbitmq
                ports:
                  - containerPort: 4369 # opens an additional port on the rabbitmq server container
                    name: epmd
                    protocol: TCP 
                  - containerPort: 25672 # opens an additional port on the rabbitmq server container
                    name: dist
                    protocol: TCP
  secretBackend:
    externalSecret:
      name: uex-admin-secret     
              
  rabbitmq:
      additionalPlugins:
        - rabbitmq_top
        - rabbitmq_shovel
        - rabbitmq_tracing