apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: {{ $.Values.rmq_cluster_name }}
  namespace: {{ $.Values.namespace }}
  labels:
    app: rabbitmq
spec:  
  replicas: 1
  terminationGracePeriodSeconds: 180 
  image: {{ $.Values.image }}  
  override:
    service:      
      spec:
        ports:
          - name: epmd 
            protocol: TCP
            port: 4369
    statefulSet:
      spec:
        template:
          spec:      
            containers:
              - name: rabbitmq
                ports:
                  - containerPort: 4369
                    name: epmd
                    protocol: TCP 
                  - containerPort: 25672
                    name: dist
                    protocol: TCP
  secretBackend:
    externalSecret:
      name: {{ $.Values.admin_secret}}  
              
  rabbitmq:
      additionalPlugins:               
        - rabbitmq_shovel
        - rabbitmq_shovel_management
        - rabbitmq_tracing        
        
       