apiVersion: v1
data:
  uex-init-job.sh: "#!/bin/bash\nset -e\necho \"Checking RabbitMQ node status for
    node : rabbit@rmq-message-broker-server-0.rmq-message-broker-nodes.apps\"\n\nMAX_RETRIES=\"${MAX_RETRIES:-10}\"\nSLEEP_SECONDS=\"${SLEEP_SECONDS:-10}\"\nRABBITMQ_STATUS=false\n\nfor
    i in $(seq 1 \"$MAX_RETRIES\"); do\n  if rabbitmqctl -n rabbit@rmq-message-broker-server-0.rmq-message-broker-nodes.apps
    -l status > /dev/null 2>&1; then\n    echo \"RabbitMQ is ready.\"\n    RABBITMQ_STATUS=true\n
    \   break\n  fi\n\n  echo \"[$i/$MAX_RETRIES] RabbitMQ not ready. Retrying in
    ${SLEEP_SECONDS}s...\"  \n\n  # Don't sleep on the last attempt\n  if [ \"$i\"
    -lt \"$MAX_RETRIES\" ]; then\n    sleep \"$SLEEP_SECONDS\"\n  fi\ndone\n\nif [
    \"$RABBITMQ_STATUS\" != true ]; then\n  echo \"RabbitMQ never became ready after
    $((MAX_RETRIES * SLEEP_SECONDS)) seconds.\"  \n  exit 1\nfi\n\necho \"Enabling
    message tracing...\"\nrabbitmqctl -n rabbit@rmq-message-broker-server-0.rmq-message-broker-nodes.apps
    -l trace_on -p uex"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: uex-init-job-config
