#folder name in vault
# This values.yaml is for Admin user of RMQ exchange
admin_users: 
  name:
    - uex-admin

userSettings:
  uex-admin:
    tags:
    - management
    - administrator
    permissions:
      configure: .*
      write: .*
      read: .* 
    vhost: uex    